/*
 * This file is generated by jOOQ.
 */
package ru.aperepelkin.revolut.account.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import ru.aperepelkin.revolut.account.jooq.tables.Accounts;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONSTRAINT_INDEX_A = Indexes0.CONSTRAINT_INDEX_A;
    public static final Index PRIMARY_KEY_A = Indexes0.PRIMARY_KEY_A;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONSTRAINT_INDEX_A = Internal.createIndex("CONSTRAINT_INDEX_A", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.NUMBER }, true);
        public static Index PRIMARY_KEY_A = Internal.createIndex("PRIMARY_KEY_A", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.ID }, true);
    }
}
