/*
 * This file is generated by jOOQ.
 */
package ru.aperepelkin.revolut.account.jooq;


import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import ru.aperepelkin.revolut.account.jooq.tables.Accounts;
import ru.aperepelkin.revolut.account.jooq.tables.records.AccountsRecord;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountsRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
    public static final UniqueKey<AccountsRecord> CONSTRAINT_AF = UniqueKeys0.CONSTRAINT_AF;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountsRecord> CONSTRAINT_A = Internal.createUniqueKey(Accounts.ACCOUNTS, "CONSTRAINT_A", Accounts.ACCOUNTS.ID);
        public static final UniqueKey<AccountsRecord> CONSTRAINT_AF = Internal.createUniqueKey(Accounts.ACCOUNTS, "CONSTRAINT_AF", Accounts.ACCOUNTS.NUMBER);
    }
}
