/*
 * This file is generated by jOOQ.
 */
package ru.aperepelkin.revolut.account.jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import javax.annotation.Generated;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.account_id_seq</code>
     */
    public static final Sequence<Long> ACCOUNT_ID_SEQ = new SequenceImpl<Long>("account_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
