/*
 * This file is generated by jOOQ.
 */
package ru.aperepelkin.revolut.account.jooq;


import ru.aperepelkin.revolut.account.jooq.tables.Accounts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNTS</code>.
     */
    public static final Accounts ACCOUNTS = ru.aperepelkin.revolut.account.jooq.tables.Accounts.ACCOUNTS;
}
